version: '3.8'

services:
  web:
    build: .
    command: python django_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_project
    ports: 
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13.2